exports.checmicalElements = [
  { z: 1, symbol: "H", element: "Hydrogen", originName: "composed of the Greek elements hydro- and -gen meaning 'water-forming'", group: "1", period: 1 },
  { z: 2, symbol: "He", element: "Helium", originName: "the Greek helios, 'sun'", group: "18", period: 1 },
  { z: 3, symbol: "Li", element: "Lithium", originName: "the Greek lithos, 'stone'", group: "1", period: 2 },
  { z: 4, symbol: "Be", element: "Beryllium", originName: "beryl, a mineral", group: "2", period: 2 },
  { z: 5, symbol: "B", element: "Boron", originName: "borax, a mineral", group: "13", period: 2 },
  { z: 6, symbol: "C", element: "Carbon", originName: "the Latin carbo, 'coal'", group: "14", period: 2 },
  { z: 7, symbol: "N", element: "Nitrogen", originName: "the Greek nitron and '-gen' meaning 'niter-forming'", group: "15", period: 2 },
  { z: 8, symbol: "O", element: "Oxygen", originName: "from the Greek oxy-, both 'sharp' and 'acid', and -gen, meaning 'acid-forming'", group: "16", period: 2 },
  { z: 9, symbol: "F", element: "Fluorine", originName: "the Latin fluere, 'to flow'", group: "17", period: 2 },
  { z: 10, symbol: "Ne", element: "Neon", originName: "the Greek neos, meaning 'new'", group: "18", period: 2 },
  { z: 11, symbol: "Na", element: "Sodium", originName: "the English word soda (natrium in Latin)", group: "1", period: 3 },
  { z: 12, symbol: "Mg", element: "Magnesium", originName: "Magnesia, a district of Eastern Thessaly in Greece", group: "2", period: 3 },
  { z: 13, symbol: "Al", element: "Aluminium", originName: "from alumina, a compound (originally aluminum)", group: "13", period: 3 },
  { z: 14, symbol: "Si", element: "Silicon", originName: "from the Latin silex, 'flint' (originally silicium)", group: "14", period: 3 },
  { z: 15, symbol: "P", element: "Phosphorus", originName: "the Greek phoosphoros, 'carrying light'", group: "15", period: 3 },
  { z: 16, symbol: "S", element: "Sulfur", originName: "the Latin sulphur, 'fire and brimstone'", group: "16", period: 3 },
  { z: 17, symbol: "Cl", element: "Chlorine", originName: "the Greek chloros, 'greenish yellow'", group: "17", period: 3 },
  { z: 18, symbol: "Ar", element: "Argon", originName: "the Greek argos, 'idle'", group: "18", period: 3 },
  { z: 19, symbol: "K", element: "Potassium", originName: "New Latin potassa, 'potash' (kalium in Latin)", group: "1", period: 4 },
  { z: 20, symbol: "Ca", element: "Calcium", originName: "the Latin calx, 'lime'", group: "2", period: 4 },
  { z: 21, symbol: "Sc", element: "Scandium", originName: "Scandia, the Latin name for Scandinavia", group: "3", period: 4 },
  { z: 22, symbol: "Ti", element: "Titanium", originName: "Titans, the sons of the Earth goddess of Greek mythology", group: "4", period: 4 },
  { z: 23, symbol: "V", element: "Vanadium", originName: "Vanadis, an Old Norse name for the Scandinavian goddess Freyja", group: "5", period: 4 },
  { z: 24, symbol: "Cr", element: "Chromium", originName: "the Greek chroma, 'color'", group: "6", period: 4 },
  { z: 25, symbol: "Mn", element: "Manganese", originName: "corrupted from magnesia negra, see Magnesium", group: "7", period: 4 },
  { z: 26, symbol: "Fe", element: "Iron", originName: "English word (ferrum in Latin)", group: "8", period: 4 },
  { z: 27, symbol: "Co", element: "Cobalt", originName: "the German word Kobold, 'goblin'", group: "9", period: 4 },
  { z: 28, symbol: "Ni", element: "Nickel", originName: "from a mischievous sprite of German miner mythology , Nickel", group: "10", period: 4 },
  { z: 29, symbol: "Cu", element: "Copper", originName: "English word (Latin cuprum)", group: "11", period: 4 },
  { z: 30, symbol: "Zn", element: "Zinc", originName: "German word Zinke (prong, tooth)", group: "12", period: 4 },
  { z: 31, symbol: "Ga", element: "Gallium", originName: "Gallia, the Latin name for France", group: "13", period: 4 },
  { z: 32, symbol: "Ge", element: "Germanium", originName: "Germania, the Latin name for Germany", group: "14", period: 4 },
  { z: 33, symbol: "As", element: "Arsenic", originName: "English word (Latin arsenicum)", group: "15", period: 4 },
  { z: 34, symbol: "Se", element: "Selenium", originName: "the Greek selene, 'moon'", group: "16", period: 4 },
  { z: 35, symbol: "Br", element: "Bromine", originName: "the Greek bromos, 'stench'", group: "17", period: 4 },
  { z: 36, symbol: "Kr", element: "Krypton", originName: "the Greek kryptos, 'hidden'", group: "18", period: 4 },
  { z: 37, symbol: "Rb", element: "Rubidium", originName: "the Latin rubidus, 'deep red'", group: "1", period: 5 },
  { z: 38, symbol: "Sr", element: "Strontium", originName: "Strontian, a small town in Scotland", group: "2", period: 5 },
  { z: 39, symbol: "Y", element: "Yttrium", originName: "Ytterby, Sweden", group: "3", period: 5 },
  { z: 40, symbol: "Zr", element: "Zirconium", originName: "Persian Zargun, 'gold-colored'; German Zirkoon, 'jargoon'", group: "4", period: 5 },
  { z: 41, symbol: "Nb", element: "Niobium", originName: "Niobe, daughter of king Tantalus from Greek mythology", group: "5", period: 5 },
  { z: 42, symbol: "Mo", element: "Molybdenum", originName: "the Greek molybdos meaning 'lead'", group: "6", period: 5 },
  { z: 43, symbol: "Tc", element: "Technetium", originName: "the Greek tekhnètos meaning 'artificial'", group: "7", period: 5 },
  { z: 44, symbol: "Ru", element: "Ruthenium", originName: "Ruthenia, the New Latin name for Russia", group: "8", period: 5 },
  { z: 45, symbol: "Rh", element: "Rhodium", originName: "the Greek rhodos, meaning 'rose coloured'", group: "9", period: 5 },
  { z: 46, symbol: "Pd", element: "Palladium", originName: "the then recently discovered asteroid Pallas, considered a planet at the time", group: "10", period: 5 },
  { z: 47, symbol: "Ag", element: "Silver", originName: "English word (argentum in Latin)", group: "11", period: 5 },
  { z: 48, symbol: "Cd", element: "Cadmium", originName: "the New Latin cadmia, from King Kadmos", group: "12", period: 5 },
  { z: 49, symbol: "In", element: "Indium", originName: "indigo", group: "13", period: 5 },
  { z: 50, symbol: "Sn", element: "Tin", originName: "English word (stannum in Latin)", group: "14", period: 5 },
  { z: 51, symbol: "Sb", element: "Antimony", originName: "uncertain: perhaps from the Greek anti, 'against', and monos, 'alone', or the Old French antimoine, 'Monk's bane' (stibium in Latin)", group: "15", period: 5 },
  { z: 52, symbol: "Te", element: "Tellurium", originName: "Latin tellus, 'earth'", group: "16", period: 5 },
  { z: 53, symbol: "I", element: "Iodine", originName: "French iode (after the Greek ioeides, 'violet')", group: "17", period: 5 },
  { z: 54, symbol: "Xe", element: "Xenon", originName: "the Greek xenos, 'strange'", group: "18", period: 5 },
  { z: 55, symbol: "Cs", element: "Caesium", originName: "the Latin caesius, 'sky blue'", group: "1", period: 6 },
  { z: 56, symbol: "Ba", element: "Barium", originName: "the Greek barys, 'heavy'", group: "2", period: 6 },
  { z: 57, symbol: "La", element: "Lanthanum", originName: "the Greek lanthanein, 'to lie hidden'", group: "3", period: 6 },
  { z: 58, symbol: "Ce", element: "Cerium", originName: "the then recently discovered asteroid Ceres, considered a planet at the time", group: "n/a", period: 6 },
  { z: 59, symbol: "Pr", element: "Praseodymium", originName: "the Greek praseios didymos meaning 'green twin'", group: "n/a", period: 6 },
  { z: 60, symbol: "Nd", element: "Neodymium", originName: "the Greek neos didymos meaning 'new twin'", group: "n/a", period: 6 },
  { z: 61, symbol: "Pm", element: "Promethium", originName: "Prometheus of Greek mythology who stole fire from the Gods and gave it to humans", group: "n/a", period: 6 },
  { z: 62, symbol: "Sm", element: "Samarium", originName: "Samarskite, the name of the mineral from which it was first isolated", group: "n/a", period: 6 },
  { z: 63, symbol: "Eu", element: "Europium", originName: "Europe", group: "n/a", period: 6 },
  { z: 64, symbol: "Gd", element: "Gadolinium", originName: "Johan Gadolin, chemist, physicist and mineralogist", group: "n/a", period: 6 },
  { z: 65, symbol: "Tb", element: "Terbium", originName: "Ytterby, Sweden", group: "n/a", period: 6 },
  { z: 66, symbol: "Dy", element: "Dysprosium", originName: "the Greek dysprositos, 'hard to get'", group: "n/a", period: 6 },
  { z: 67, symbol: "Ho", element: "Holmium", originName: "Holmia, the New Latin name for Stockholm", group: "n/a", period: 6 },
  { z: 68, symbol: "Er", element: "Erbium", originName: "Ytterby, Sweden", group: "n/a", period: 6 },
  { z: 69, symbol: "Tm", element: "Thulium", originName: "Thule, the ancient name for Scandinavia", group: "n/a", period: 6 },
  { z: 70, symbol: "Yb", element: "Ytterbium", originName: "Ytterby, Sweden", group: "n/a", period: 6 },
  { z: 71, symbol: "Lu", element: "Lutetium", originName: "Lutetia, the Latin name for Paris", group: "n/a", period: 6 },
  { z: 72, symbol: "Hf", element: "Hafnium", originName: "Hafnia, the New Latin name for Copenhagen", group: "4", period: 6 },
  { z: 73, symbol: "Ta", element: "Tantalum", originName: "King Tantalus, father of Niobe from Greek mythology", group: "5", period: 6 },
  { z: 74, symbol: "W", element: "Tungsten", originName: "the Swedish tung sten, 'heavy stone' (W is wolfram, the old name of the tungsten mineral wolframite)", group: "6", period: 6 },
  { z: 75, symbol: "Re", element: "Rhenium", originName: "Rhenus, the Latin name for the river Rhine", group: "7", period: 6 },
  { z: 76, symbol: "Os", element: "Osmium", originName: "the Greek osmè, meaning 'smell'", group: "8", period: 6 },
  { z: 77, symbol: "Ir", element: "Iridium", originName: "Iris, the Greek goddess of the rainbow", group: "9", period: 6 },
  { z: 78, symbol: "Pt", element: "Platinum", originName: "the Spanish platina, meaning 'little silver'", group: "10", period: 6 },
  { z: 79, symbol: "Au", element: "Gold", originName: "English word (aurum in Latin)", group: "11", period: 6 },
  { z: 80, symbol: "Hg", element: "Mercury", originName: "the New Latin name mercurius, named after the Roman god (Hg from former name hydrargyrum, from Greek hydr-, 'water', and argyros, 'silver')", group: "12", period: 6 },
  { z: 81, symbol: "Tl", element: "Thallium", originName: "the Greek thallos, 'green twig'", group: "13", period: 6 },
  { z: 82, symbol: "Pb", element: "Lead", originName: "English word (plumbum in Latin)", group: "14", period: 6 },
  { z: 83, symbol: "Bi", element: "Bismuth", originName: "Uncertain, possibly Arabic or German", group: "15", period: 6 },
  { z: 84, symbol: "Po", element: "Polonium", originName: "Named after the home country of Marie Curie (Polonia, Latin for Poland), who is also the discoverer of Radium", group: "16", period: 6 },
  { z: 85, symbol: "At", element: "Astatine", originName: "the Greek astatos, 'unstable'", group: "17", period: 6 },
  { z: 86, symbol: "Rn", element: "Radon", originName: "From radium, as it was first detected as an emission from radium during radioactive decay", group: "18", period: 6 },
  { z: 87, symbol: "Fr", element: "Francium", originName: "Francia, the New Latin name for France", group: "1", period: 7 },
  { z: 88, symbol: "Ra", element: "Radium", originName: "the Latin radius, 'ray'", group: "2", period: 7 },
  { z: 89, symbol: "Ac", element: "Actinium", originName: "the Greek aktis, 'ray'", group: "3", period: 7 },
  { z: 90, symbol: "Th", element: "Thorium", originName: "Thor, the Scandinavian god of thunder", group: "n/a", period: 7 },
  { z: 91, symbol: "Pa", element: "Protactinium", originName: "the Greek protos, 'first', and actinium, which is produced through the radioactive decay of protactinium", group: "n/a", period: 7 },
  { z: 92, symbol: "U", element: "Uranium", originName: "Uranus, the seventh planet in the Solar System", group: "n/a", period: 7 },
  { z: 93, symbol: "Np", element: "Neptunium", originName: "Neptune, the eighth planet in the Solar System", group: "n/a", period: 7 },
  { z: 94, symbol: "Pu", element: "Plutonium", originName: "Pluto, a dwarf planet in the Solar System (then considered the ninth planet)", group: "n/a", period: 7 },
  { z: 95, symbol: "Am", element: "Americium", originName: "The Americas, as the element was first synthesized on the continent, by analogy with europium", group: "n/a", period: 7 },
  { z: 96, symbol: "Cm", element: "Curium", originName: "Pierre Curie, a physicist, and Marie Curie, a physicist and chemist, named after great scientists by analogy with gadolinium", group: "n/a", period: 7 },
  { z: 97, symbol: "Bk", element: "Berkelium", originName: "Berkeley, California, where the element was first synthesized, by analogy with terbium", group: "n/a", period: 7 },
  { z: 98, symbol: "Cf", element: "Californium", originName: "California, where the element was first synthesized", group: "n/a", period: 7 },
  { z: 99, symbol: "Es", element: "Einsteinium", originName: "Albert Einstein, physicist", group: "n/a", period: 7 },
  { z: 100, symbol: "Fm", element: "Fermium", originName: "Enrico Fermi, physicist", group: "n/a", period: 7 },
  { z: 101, symbol: "Md", element: "Mendelevium", originName: "Dmitri Mendeleev, chemist and inventor", group: "n/a", period: 7 },
  { z: 102, symbol: "No", element: "Nobelium", originName: "Alfred Nobel, chemist, engineer, innovator, and armaments manufacturer", group: "n/a", period: 7 },
  { z: 103, symbol: "Lr", element: "Lawrencium", originName: "Ernest O. Lawrence, physicist", group: "n/a", period: 7 },
  { z: 104, symbol: "Rf", element: "Rutherfordium", originName: "Ernest Rutherford, chemist and physicist", group: "4", period: 7 },
  { z: 105, symbol: "Db", element: "Dubnium", originName: "Dubna, Russia", group: "5", period: 7 },
  { z: 106, symbol: "Sg", element: "Seaborgium", originName: "Glenn T. Seaborg, scientist", group: "6", period: 7 },
  { z: 107, symbol: "Bh", element: "Bohrium", originName: "Niels Bohr, physicist", group: "7", period: 7 },
  { z: 108, symbol: "Hs", element: "Hassium", originName: "Hesse, Germany, where the element was first synthesized", group: "8", period: 7 },
  { z: 109, symbol: "Mt", element: "Meitnerium", originName: "Lise Meitner, physicist", group: "9", period: 7 },
  { z: 110, symbol: "Ds", element: "Darmstadtium", originName: "Darmstadt, Germany, where the element was first synthesized", group: "10", period: 7 },
  { z: 111, symbol: "Rg", element: "Roentgenium", originName: "Wilhelm Conrad Röntgen, physicist", group: "11", period: 7 },
  { z: 112, symbol: "Cn", element: "Copernicium", originName: "Nicolaus Copernicus, astronomer", group: "12", period: 7 },
  { z: 113, symbol: "Nh", element: "Nihonium", originName: "the Japanese name for Japan, Nihon, where the element was first synthesized", group: "13", period: 7 },
  { z: 114, symbol: "Fl", element: "Flerovium", originName: "Flerov Laboratory of Nuclear Reactions, part of JINR where the element was synthesized; itself named for Georgy Flyorov, physicist", group: "14", period: 7 },
  { z: 115, symbol: "Mc", element: "Moscovium", originName: "Moscow Oblast, Russia, where the element was first synthesized", group: "15", period: 7 },
  { z: 116, symbol: "Lv", element: "Livermorium", originName: "Lawrence Livermore National Laboratory (in Livermore, California) which collaborated with JINR on its synthesis", group: "16", period: 7 },
  { z: 117, symbol: "Ts", element: "Tennessine", originName: "Tennessee, United States", group: "17", period: 7 },
  { z: 118, symbol: "Og", element: "Oganesson", originName: "Yuri Oganessian, physicist", group: "18", period: 7 }
]